---
# see http://molecule.readthedocs.io/en/stable-1.9/usage.html
language: python

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - vagrant

install:
  - pip install -r requirements.txt

before_script:
  - cookiecutter -f --no-input . input role_name=tree project_name=test

script:
  - cd test
  - molecule test

# see http://docs.ansible.com/ansible/galaxy.html#setup-travis-integrations
#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
