# vim: sw=2 ts=2 et :
---
# see http://molecule.readthedocs.io/en/stable-1.9/usage.html
language: python

sudo: required

services:
  - docker

install:
  - pip install -r https://raw.githubusercontent.com/nephelaiio/ansible-role-requirements/master/requirements.txt

script:
  - pytest -s
