# vim: sw=2 ts=2 et :
---
# see http://molecule.readthedocs.io/en/stable-1.9/usage.html
language: python

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

sudo: required

services:
  - docker

install:
  - pip install -r https://raw.githubusercontent.com/nephelaiio/ansible-role-requirements/master/requirements.txt

script:
  - pytest -s
