---
# - name: restart {{ cookiecutter.role_name }}
#   service:
#     name: "{{ '{{' }} {{ cookiecutter.role_name | replace('-', '_') }}_service_name {{ '}}' }}"
#     state: restarted
#   become: "yes"
#   when: {{ cookiecutter.role_name | replace('-', '_') }}_service_name is defined
