---
- hosts: all
  pre_tasks:
    - name: "installing which"
      action: yum
              name=which
              state=installed
      when: ansible_distribution == 'CentOS'
    - name: "installing wget"
      action: apt
              name=wget
              state=installed
      when: ansible_distribution == 'Debian'
  roles:
    - role: {{ cookiecutter.role_name }}
