---
# Include variable definitions
{% raw -%}
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distrubition }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
{%- endraw %}
  tags:
    - {{ cookiecutter.role_name }}

# Install packages
{% if cookiecutter.package_install -%}
- name: install {{ cookiecutter.role_name }} packages
  package: name="{{ '{{' }} item {{ '}}' }}" state="{{ '{{' }} {{ cookiecutter.role_name}}_packages_state {{ '}}' }}"
  with_items:
    - "{{ '{{' }} {{ cookiecutter.role_name }}_packages {{ '}}' }}"
  become: yes
  tags:
    - {{ cookiecutter.role_name }} 
{%- endif %}

# Set up configuration file
{% if cookiecutter.package_config -%}
- name: configure {{ cookiecutter.role_name }}
  template: >
    src={{ cookiecutter.role_name }}_conf_template
    dest="{{ '{{' }} {{ cookiecutter.role_name }}_conf_path {{ '}}' }}"
  become: no
  when: {{ cookiecutter.role_name }}_conf_path is defined
  tags:
    - {{ cookiecutter.role_name }}
    - {{ cookiecutter.role_name }}_conf
{%- endif %}
